### ISSUE TITLE
Request for arm64 package release

### ISSUE THREAD

**Issue by embeeweezer** [dnglab/dnglab#12]
Could you please include an arm64 build in your releases?! Sheer lack of compiling knowledge is the reason I'm asking ;) BTW I'm thrilled by the project and hope to see it grow! Thanks!

**Comment by cytrinox** [comment]
@embeeweezer Could you please test https://github.com/dnglab/dnglab/releases/tag/v0.1.0-rc3 and report if this arm64 build works for you.

**Comment by embeeweezer** [comment]
Looks like the arm64 build works, thanks! I also compared the filesizes to those of the Adobe DNG Converter:
Original CR3: 35.6MB
dnglab (noembedded,compressed lossless): 38.4MB
Adobe (lossless): 31.5MB
I'm not sure if these numbers are expected?

**Comment by cytrinox** [comment]
Yes, this is expected. I only have implemented 1-component lossless compression. Adobe uses 2-component compression which has a litte bit better ratio. But my 2-component implementation is buggy, so not included in release.

**Comment by embeeweezer** [comment]
Ok that's clear, thank you!

**Comment by cytrinox** [comment]
@embeeweezer Latest rc4 contains an improved LJPEG compressor including 2-component compression. https://github.com/dnglab/dnglab/releases/tag/v0.1.0-rc4

**Comment by embeeweezer** [comment]
That's great!! I can confirm an average size reduction of about 5 MB compared to files produced by RC3. (Original CR3's were around 39 MB)
