### ISSUE TITLE
Support for CR3 CRAW lossy compression

### ISSUE THREAD

**Issue by neo22s** [dnglab/dnglab#13]
Hello,

Latest libraw supports Lossy compressed CR3  https://www.libraw.org/news/libraw-202101-snapshot also ART supports it https://bitbucket.org/agriggio/art/wiki/Home

Commit https://bitbucket.org/agriggio/art/commits/2663d3e887d5f92c446b4d64010765df3432df4c 

Maybe you can check the code ;)

Would be great to get this. thanks

**Comment by cytrinox** [comment]
Crx decoder in dnglab is based on libraw's cr3/crx decoder from crx.cpp. But only the parts of code I actually understand and are able do rewrite in understandable Rust code. Most of the code in crx.cpp looks like assembler code rewritten in C++. It is very difficult to understand the compression algorithm from this code.

**Comment by cytrinox** [comment]
I someone is willing to write a (de)compression algorithm specification based on the crx.cpp code it should be easy to implement the code in Rust. So far Canon has not provided any documentation and the patent for CRAW is not sufficent to understand the data structures.

**Comment by neo22s** [comment]
I have no clue about this development languages sorry :(
