### ISSUE TITLE
Lens not recognized

### ISSUE THREAD

**Issue by Heddesdorfer** [dnglab/dnglab#136]
Although listed the lens 
RF100mm F2.8 L MACRO IS USM
was not recognized:
![image](https://user-images.githubusercontent.com/91422232/162214300-ada3ac45-7484-42e1-b528-621eed5cea7f.png)
I'd had uploaded the raw file, but it didn't work - sorry.

**Comment by cytrinox** [comment]
You can test against this branch: https://github.com/dnglab/dnglab/pull/135

It includes proper RF 100mm support (at least for my RF 100 lens :smile: )

Or wait for release 0.5 which will include this branch.
