### ISSUE TITLE
Any plan on Sony ARW file support?

### ISSUE THREAD

**Issue by AlynxZhou** [dnglab/dnglab#137]
Hi, I am looking for a software to convert my Sony camera files into DNG, this project looks good, but it currently does not support ARW. Is there any plan to support it? If example of ARW files is needed, I can provide some. Thanks.

**Comment by cytrinox** [comment]
Yes, 0.5 will include ARW support, but starting with a small subset of supported cameras. You can post your camera model so I can priorize it.

**Comment by AlynxZhou** [comment]
> Yes, 0.5 will include ARW support, but starting with a small subset of supported cameras. You can post your camera model so I can priorize it.

Thank you! Currently I am using ILCE-7SM3 and ILCE-7RM3.

**Comment by AlynxZhou** [comment]
I just uploaded compressed and uncompressed 14 bit RAW files I took last weekend, although it's a cloudy day so no blue sky here :-P.

I forget to take APS-C crop photos, I'll take them soon and upload, ILCE-7SM3 keeps 14 bit on electric shutter so there is no need for 12 bit RAW.

**Comment by lclevy** [comment]
Hi,
I just published a description of Sony RAW file formats here : https://github.com/lclevy/sony_raw
feedback is welcome !

**Comment by cytrinox** [comment]
@lclevy That's great news, the sony structures are not well documented so far.

Btw I already added full Sony support to the main branch, just forgot about this ticket.

**Comment by cytrinox** [comment]
@AlynxZhou Sony support is available in main branch and ready for the next release. If you can compile version on our own, I would be happy about feedback (please open new issues for that). Thanks!

**Comment by lclevy** [comment]
Could you please read the document and give me your feedback?

**Comment by cytrinox** [comment]
@lclevy Sure I do. I've Panasonic and Fuji support in the pipeline which I want to finish first. Then I've an open issue with Sony ARQ support (multishots). I think that's a good time to come back to your document :+1:

**Comment by lclevy** [comment]
Thank you

**Comment by lclevy** [comment]
Yes, and to add ARQ description

**Comment by CorValidum** [comment]
Hi, have I missed something or ARW files are still not supported? I added few of my a6700 files to test the software but it was not able to open them...
