### ISSUE TITLE
Version 0.4.0: thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', bin/dnglab/src/dnggen.rs:144:66

### ISSUE THREAD

**Issue by arbv** [dnglab/dnglab#140]
I had problems converting the attached CR3 file. The converted DNG file size is 0 bytes.

```
artem@zorrobook:~/report$ RUST_BACKTRACE=full dnglab convert ./IMG_4959.CR3 ./IMG_4959.DNG
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', bin/dnglab/src/dnggen.rs:144:66
stack backtrace:
   0:     0x5613302aca4c - <unknown>
   1:     0x5613302d046c - <unknown>
   2:     0x5613302a5cc5 - <unknown>
   3:     0x5613302ae620 - <unknown>
   4:     0x5613302ae1d5 - <unknown>
   5:     0x5613302aecd4 - <unknown>
   6:     0x5613302ae782 - <unknown>
   7:     0x5613302acef4 - <unknown>
   8:     0x5613302ae719 - <unknown>
   9:     0x56132ffaa9e1 - <unknown>
  10:     0x56132ffaa92d - <unknown>
  11:     0x56132ffe9f44 - <unknown>
  12:     0x56132ffcab4c - <unknown>
  13:     0x56132ffd6a74 - <unknown>
  14:     0x56133004a4d5 - <unknown>
  15:     0x56133000696c - <unknown>
  16:     0x5613300993d5 - <unknown>
  17:     0x56133008d0fe - <unknown>
  18:     0x5613300abfd8 - <unknown>
  19:     0x5613302b2c53 - <unknown>
  20:     0x7f237cb465c2 - start_thread
  21:     0x7f237cbcb584 - __clone
  22:                0x0 - <unknown>
Converted 0/1 files, 1 failed:
   /home/artem/Pictures/raw academy/report/IMG_4959.CR3
Total time: 0.73s

```
The previous version (0.3.1) produced the usable result, despite lacking support for Canon EF-S 17-55mm f/2.8 IS USM Lens (see #108).

[Here is a link to the CR3 file](https://mega.nz/file/D8FzGRSC#J0oY21uSuV56Uwiqe_av7zVpmWczwZUbl5ZuFk08yZw)

For some reason Github did not want to accept my CR3 file upload, nor a zip file which included it.

**Comment by arbv** [comment]
BTW, the file attached in #108 bug report also triggers the bug.

**Comment by cytrinox** [comment]
Thanks for your bug report, but I can not reproduce it with current main branch. A lot of code refactoring was done since 0.4 on main. Looks like this is already fixed :smile:

**Comment by arbv** [comment]
That is great!

Are there any plans to release the next version soon?

Again, thanks for your hard work. You are working on a really missing peace of software!

**Comment by arbv** [comment]
Just in case: the version from main does not abort, so this one could be closed.
