### ISSUE TITLE
Add support for lens 'EF80-200mm f/4.5-5.6 II' from Canon

### ISSUE THREAD

**Issue by appuchias** [dnglab/dnglab#149]
When converting the photo, the error `Unknown lens model: 'EF80-200mm f/4.5-5.6 II'. Please open an issue at https://github.com/dnglab/dnglab/issues and provide the RAW file` was raised.

I add the image as an attachment below.

[IMG_20220416_1539.zip](https://github.com/dnglab/dnglab/files/8548260/IMG_20220416_1539.zip)

**Comment by cytrinox** [comment]
Fixed in 0.5 release
