### ISSUE TITLE
Add support for lens 'EF24-70mm f/2.8L USM' from Canon

### ISSUE THREAD

**Issue by appuchias** [dnglab/dnglab#150]
When converting the photo, the error `Unknown lens model: 'EF24-70mm f/2.8L USM'. Please open an issue at https://github.com/dnglab/dnglab/issues and provide the RAW file` was raised.

I add the image as an attachment below.

[IMG_1685.zip](https://github.com/dnglab/dnglab/files/8548397/_MG_1685.zip)

**Comment by cytrinox** [comment]
Fixed in 0.5 release
