### ISSUE TITLE
2000d RAW will not open

### ISSUE THREAD

**Issue by blue-devil-93** [dnglab/dnglab#179]
The RAW image created by 2000D will not open.

**Comment by blue-devil-93** [comment]
Its a normal CR2 Raw.
Here an example file:
https://filehorst.de/download_mobile.php?file=dqEflfBh

I often use an adapter ring to mount m42 lenses but there has to be a way to deocde the i.ages uses dnglab. If you can use cr2 and cr3 raws with the software

**Comment by cytrinox** [comment]
Fixed in current main branch.
