### ISSUE TITLE
Any chance to get braw to dng or proresraw to dng ? This is already possible in other programs 

### ISSUE THREAD

**Issue by 2blackbar** [dnglab/dnglab#205]
PRores raw to dng is possible on mac app called raw convertor    https://apps.apple.com/us/app/raw-convertor/id1598580439?mt=12
braw to dng is possible with fast cinema dng processor (tried with 8k braw and works)   https://www.fastcinemadng.com/
What do You think ?

**Comment by cytrinox** [comment]
Are there any public specs for these formats & codecs? If yes, could you please link/attach them in this issue, thank you.
