### ISSUE TITLE
Converted output file extension unexpectedly lowercase

### ISSUE THREAD

**Issue by Kadigan** [dnglab/dnglab#209]
Command: `dnglab convert "/Volumes/NVMe/___WYJAZDY___/2022-07-20.IWANICZEK 20 lat/COMMON_SRC/AP2I1531.CR3" "/Volumes/NVMe/___WYJAZDY___/2022-07-20.IWANICZEK 20 lat/RAW_WYBRANE/AP2I1531.DNG"`

Expected resultant filename: `AP2I1531.DNG`

Actual resultant filename: `AP2I1531.dng`

This is reflected by the CLI output:

```
Writing DNG output file: /Volumes/NVMe/___WYJAZDY___/2022-07-20.IWANICZEK 20 lat/RAW_WYBRANE/AP2I1531.dng
Converted 1/1 files
Total time: 7.46s
```

dnglab version 0.5.0

**Comment by cytrinox** [comment]
This bug needs more code changes as supposed. Will take this for 0.6.x
