### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by paolobenve** [dnglab/dnglab#210]
The main github page doesn't explain if it has to be compiled, interpreted.... what/where are the excutables?

Thank you for adding this explications!

**Comment by Kadigan** [comment]
If you wish to build from source, the whole thing is written in RUST. Once you have a RUST compiler and `cargo`, download the sources and run `cargo build --release`. You should have the binaries in `target/release`.

**Comment by gariac** [comment]
This should be in the release notes. The cargo build --release worked fine.  Probably it is best not to move the binaries to /usr/local/bin if the devs are going to add notes on compilation.
