### ISSUE TITLE
Dng from IIQ present artifact in Dt 

### ISSUE THREAD

**Issue by dim162** [dnglab/dnglab#215]
IIQ phase one file are not well-supported by rawspeed. I try dnglab & the dng obtained is perfectly opened in Dt, until I rotate it.

**Comment by cytrinox** [comment]
Please provide more information, it's more likely  that darktable and/or your graphics driver can't handle such big images well on your system. There is no special magic in DNG, if the image is properly rendered in landscape mode, the pixel & metadata are correct.
You could also share the IIQ and DNG files so verification is possible on other systems.

**Comment by dim162** [comment]
Ubuntu studio 22.04.01, kernel 5.15, nvidia driver 470, opencl, amd Rijzen 7 4.2 gHz, nvidia gtx 1050 Ti 4gb, gtx 760 2gb, memory 32gb 3.4 gHz. R-darktable with opencl. 
The system can manipulate natively, QII files (with artifacts, rawspeed doesn't support it well), DNG from Vuescan, twice & triple the size of those from Dnglab, without artifact. In ART, i have no problems.
I put IIQ P65+ on https://raw.pixls.us/ .  DNG, copie screen, ... are there  [](https://www.dropbox.com/sh/ddm1bzgo14vqlcg/AAAQx_pd7ifLvxz7dwHITnnza?dl=0). 
The artifacts appear when in rdarktable, the view is in portrait & full screen or window max. This is the only DNG & RAW files, i had, which give this.

**Comment by cytrinox** [comment]
I've loaded test.dng into my local darktable 4.0 build, but unable to reproduce your issue. As the pixels stored in dng are independend from any rotation, I can't imagine any reason related to dnglab. The only advice I can give you for now is to open an issue at rdarktable.
