### ISSUE TITLE
Option to output multiple DNG's (one for every frame) when converting Canon CRM files (Canon raw cinema format)

### ISSUE THREAD

**Issue by Leevas** [dnglab/dnglab#219]
This is the first program(as far as I know) that actually can convert canon raw cinema file (CRM) to DNG.
Only downside is, I only get (access to) the first frame. 
When converting a CRM file with DNGlab, I end up with a massive DNG file, slightly bigger in size then the CRM file (for example a 450Mb CRM file becomes a 480Mb DNG file).
But when opened in several raw editors, only the first frame is showed, and no way to select a different sub-frame (Rawtherapee has an option for selecting sub frames for files which contain multiple frames, but this options doesn't show up with resulting dng's from DNGlab.
So the conversion of CRM to DNG is already working in DNGlab, if it can produce a separate dng for every frame (with suffix of "frame_000000" and counting up, it would be brilliant.

Why would one convert canon raw CRM file to a DNG sequence ? Well this opens the way to get highlight recovery in Davinci resolve (highlight recovery is available for DNG, but there is no highlight recovery option for CRM files...)
Plus there isn't much software that supports CRM files, many raw photo editors have unique options compared to Davinci Resolve.

In case you need access to CRM files, here's a link to some CRM files.
[https://drive.google.com/drive/folders/1orh98TR0jyVYRVLGxAnZh7-1_9E3MNF-](url)

**Comment by cytrinox** [comment]
Please have a look at the README for convert command,  **--image-index all** and **--embed-raw false** should perfectly handle your case. The first command generates a sequence of DNGs for all embedded frames, the second prevents embedding the original CRM file into DNG (that's why it become so big).

**Comment by cytrinox** [comment]
Just for reference: **-image-index all** will not work for dual-pixel raw files. The second image for a dual pixel raw is stored in a separate *trak* element. In normal operation, dnglab tries to resolve the *trak* index from CR3 metadata, but you can override the index with environment variable **RAWLER_CRX_RAW_TRAK**. Usually the highres raw data is in trak 3 (index 2), dual pixel data is in trak 5 (index 4). See https://github.com/lclevy/canon_cr3 for reference.

To select the dual pixel trak, call dnglab like this:

    $ RAWLER_CRX_RAW_TRAK=4 dnglab convert DPRAW.CR3 DPDATA.dng

**Comment by Leevas** [comment]
Thanks! 
Tested it, and adding those two options works for CRM files.
This program is brilliant.
Also thanks for the info how to extract dual raw pixel files.
Didn't read the readme file (sorry for that). But I used the --help option.
So my only complaint is that the --help command needs to be updated:

% ./dnglab --help
dnglab 0.5.1
Daniel Vogelbacher <daniel@chaospixel.com>
DNGLab - A camera raw utility and DNG converter

USAGE:
    dnglab [OPTIONS] <SUBCOMMAND>

OPTIONS:
    -d               turns on debugging mode
    -h, --help       Print help information
    -v               Print more messages
    -V, --version    Print version information

SUBCOMMANDS:
    analyze      Analyze raw image
    cameras      List supported cameras
    convert      Convert raw image(s) into dng format
    extract      Extract embedded original Raw from DNG
    ftpserver    Convert raw image(s) into dng format
    gui          Start GUI (not implemented)
    help         Print this message or the help of the given subcommand(s)
    lenses       List supported lenses

**Comment by cytrinox** [comment]
Try `dnglab convert --help`, the help for all subcommands would blow your terminal.

**Comment by Leevas** [comment]
Learning new things here by the minute ;-)
