### ISSUE TITLE
Support for EOS R10 camera

### ISSUE THREAD

**Issue by tupshin** [dnglab/dnglab#220]
I have an EOS R10, and I get a panic when trying to analyze or convert CR3 files created with this camera.

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported { what: "Unknown camera", model: "Canon EOS R10", make: "Canon", mode: "craw" }', bin/dnglab/src/analyze.rs:36:61
`
I am happy to do some legwork to help support this camera if you point me in the right direction

**Comment by cytrinox** [comment]
I need a full sample set of raw files:

 * RAW mode: ISO 100, 800, MAX (51200 / H)
 * CRAW mode: ISO 100, 800, MAX 51200 / H)
 * Burst mode: ISO 100 (see https://cam.start.canon/en/C006/manual/html/UG-05_Shooting-1_0290.html, please keep it small, 3-4 frames are sufficient)
 * Please shoot some HEIF files as well (same scene)

The scene must be properly exposed and should be something like a landscape (blue sky, white clouds, green ground, no people).

Before you do the shots, please go to menu: https://cam.start.canon/en/C006/manual/html/UG-09_Set-up_0300.html and set copyright to: "CC-0", so we can use the sample set in all raw sample databases.

Then pack them into a ZIP and upload it to wetransfer.com and post the link here. Thank you.

**Comment by cytrinox** [comment]
@tupshin Friendly reminder, I want to release 0.5.1 soon :wink:

**Comment by tupshin** [comment]
Thanks for the ping. I'll try to get you the zip contents requested this weekend.

**Comment by cytrinox** [comment]
Release date will be 25. december. If no one can contribute the required samples, 0.5.1 will not have R10 support :cry:

**Comment by paswai** [comment]
Hi @cytrinox, in case you didn't had the chance to download the files, I uploaded them again: [Link](https://we.tl/t-N7lEby7LM0)

**Comment by cytrinox** [comment]
Thanks for providing samples, this gets supported in #406

**Comment by deter0** [comment]
Any updates? I see that the PR has been merged but I am still getting the unsupported error.  `Unsupported { what: "Unknown camera", model: "Canon EOS R10", make: "Canon", mode: "craw" }`

**Comment by paswai** [comment]
Hi @deter0, to my understanding it is a milestone for the next release.
