### ISSUE TITLE
Unknown lens model: 'RF100-400mm F5.6-8 IS USM'

### ISSUE THREAD

**Issue by Heddesdorfer** [dnglab/dnglab#221]
Again no way to attach a raw file (CR3, >10MB)

**Comment by cytrinox** [comment]
This lens should be already supported in v0.5.0 https://github.com/dnglab/dnglab/blob/main/rawler/data/lenses/rf_mount/canon.toml#L236

Please re-check and if the error persists, upload an raw image example to wetransfer.com and share the link in this issue, thanks.

**Comment by Heddesdorfer** [comment]
In your link the lens is described as "RF 100-400mm F5.6-8 IS USM", 
whereas the camera stores it as      "RF100-400mm F5.6-8 IS USM".
No blank between RF and 100.

**Comment by cytrinox** [comment]
I've downloaded a CR3 with RF100-400 lens sample and can not reproduce your issue. The lens is properly detected. There is a little chance that different firmware versions of camera/lens produces obsucre lens information. If you still hit this issue, please reopen and provide a link to a CR3 file to reproduce the problem, thank you.

**Comment by Heddesdorfer** [comment]
As it is not possible to upload raw files to github (because of the file
size) I send you a download link:
 IMG_9276.CR3
<https://drive.google.com/file/d/1X17EAmsME_3nnYoSEVEvwjzs5xDJvmgr/view?usp=drive_web>

Am Mi., 2. Nov. 2022 um 20:13 Uhr schrieb Daniel Vogelbacher <
***@***.***>:
