### ISSUE TITLE
Extract command has required but redundant <FILE> argument

### ISSUE THREAD

**Issue by taylorthurlow** [dnglab/dnglab#236]
The `extract` docs (and the CLI itself) require a `<FILE>` input parameter in addition to both `<INPUT>` and `<OUTPUT>`. As far as I can tell this doesn't make sense at all and it just looks like a misconfigured CLI option - passing an empty string to the first `<FILE>` parameter seems to let me use `extract` as expected.

**Comment by cytrinox** [comment]
Yes, that's a bug introduced while refactoring clap code. Thanks for reporting.
