### ISSUE TITLE
Canon R6 Mark II support

### ISSUE THREAD

**Issue by cytrinox** [dnglab/dnglab#243]
I need a full sample set of raw files:

    RAW mode: ISO 100, 800, MAX (51200 / H)
    CRAW mode: ISO 100, 800, MAX 51200 / H)
    Burst mode: ISO 100 (please keep it small, 3-4 frames are sufficient)
    Please shoot some HEIF files as well (same scene)

The scene must be properly exposed and should be something like a landscape (blue sky, white clouds, green ground, no people).

Before you do the shots, please go to menu: https://cam.start.canon/en/C006/manual/html/UG-09_Set-up_0300.html and set copyright to: "CC-0", so we can use the sample set in all raw sample databases.

**Comment by kameit00** [comment]
Hi, here are some files, as requested...
https://cloud.mechel.de/s/ZFWWS4DmDG6Y5Qb

If you need more files or different files, no problem.

Thanks for your effort
Kai

**Comment by cytrinox** [comment]
R6II support was already in main but I forgot this issue.

Thanks for the samples anyway, more samples is always better :)
