### ISSUE TITLE
Brightness differences vs. the original RAW when previewing in LRC

### ISSUE THREAD

**Issue by Narkis25** [dnglab/dnglab#246]
Hey,

I opened in Lightroom Classic both the original [NEF raw file ](https://shotkit.com/wp-admin/admin-ajax.php?action=useyourdrive-download&account_id=101618924177038945298&id=1xSHubg6Hxmdjkxt_tn42mhVkgBtdTCR9&dl=1&listtoken=4681a5373fe2a060d953bfb350049d1c
), and the converted DNG created by the tool and found some brightness differences (the DNG appears darker), any idea why?

Original NEF Preview (appears brighter):
![Original NEF](https://i.ibb.co/JRFqqj5/Adobe-DNG.png)
DNG Lab Preview:
![DNG Lab Preview](https://i.ibb.co/Mshzv24/dnglab.png)

Thanks

**Comment by cytrinox** [comment]
One possible cause is that Lightroom might uses different black levels for the image. You can verify this by converting your raw file with Adobe DNG converter and compare the DNG Blacklevel attribute with exiftool against the dng from dnglab. Same may be true for the Whitepoint.

**Comment by narkis-feldman-imagenai** [comment]
Thanks, I'll try 🙏
