### ISSUE TITLE
Color issue converting .IIQ

### ISSUE THREAD

**Issue by GeoBI-IT** [dnglab/dnglab#278]
Hi,

I've tried to convert this .IIQ image and the result seems to be a bit off with a magenta/purple color cast.

The other image is the original .IIQ opened in capture one.

Do you have any suggestion on how to go about?

Best regards.

<img width="836" alt="original_iiq" src="https://user-images.githubusercontent.com/104266099/215181395-764f54b7-6f7f-4768-ba0e-1832200d3c73.png">

<img width="1077" alt="converted" src="https://user-images.githubusercontent.com/104266099/215181419-4549c818-f0c3-45d4-8318-b7b5f462f279.png">

**Comment by cytrinox** [comment]
Looks like wrong black level values. Please provide the raw file for a more detailed analysis.
