### ISSUE TITLE
Support for Konica/Minolta DiMage G600

### ISSUE THREAD

**Issue by Themancodes** [dnglab/dnglab#295]
I'm able to process the raw files on rawtherapee but not with this dnglab, Here is the link to sample images https://drive.google.com/drive/folders/1asANClWYjIAwfRN9cF8ZpI_B3BMb4auX?usp=sharing

**Comment by cytrinox** [comment]
rawtherapee uses libraw which supports DiMage G* models.
These files are basically JPEG containers with a fixed count of u16 raw pixel values at the end. As dnglab has no proper JPEG container parser (yet) and this camera is ~20 years old, I don't plan to add support for this camera for now, sorry.

**Comment by LibRaw** [comment]
Correction: rawtherapee (not the ART fork) uses own dcraw.c-based decoder, not LibRaw
