### ISSUE TITLE
Create DNG from JPGs / TIFFs

### ISSUE THREAD

**Issue by gwegner** [dnglab/dnglab#298]
### Discussed in https://github.com/dnglab/dnglab/discussions/294

<div type='discussions-op-text'>

<sup>Originally posted by **gwegner** April  5, 2023</sup>
Adobe Lightroom is currently AFAIK the only software that allows to convert (wrap) JPG and TIFF files into DNG.
Unfortunately they never build that feature into their DNG Converter so that it can't be used in a batch process.
https://community.adobe.com/t5/camera-raw-ideas/p-dng-converter-enable-jpg-conversion/idc-p/13477145/page/6

Would you be open to implement this in DNG Lab? That would be a massive feature!

Of course I'm well aware of the difference between Rawfiles and "Linear" files like JPG/TIFF. Also I'm aware of the fact that wrapping JPG/TIFF into DNG wouldn't create a Raw file.
But: having a Dng would allow us to use the Camera Raw engine to develop previews from the DNG + XMP file which is not possible on JPG's / TIFFs.

Thanks for considering this, of course, I'm open discuss this further!</div>

**Comment by gwegner** [comment]
Thanks for coming back to me and sorry for the delay in answer.

Let me explain the reason for that DNG from JPGs/TIFFs.

I'm the developer of a software that calculates image edits on basis of XMP files. Those XMP files need to be applied to the Source files in order to get the developed image.
Unfortunately Adobe doesn't provide a real batch process for this, that's why I use the Adobe DNG Converter to create a DNG from the Image File (Raw and DNG works here as input) - this makes the DNG Converter also embed a preview with the developed image. It's all about this preview that I'm using then for visualization of the edits.

Unfortunately, while you can have Lightroom develop JPG/TIFF+XMP in order to get the image developed with the edits in the XMP, the DNG Converter won't alllow JPG/TIFF+XMP to be converted, therefore currently there is no batch option to get a preview for JPGs/TIFFs.

The work around currently is, to bring the JPG sequence into Lighroom and use Lightroom's internal function create a DNG from the JPG/TIFF. Then those DNGs can again be fed into the DNG Converter to get the developed previews.

That process is quite sophisticated, but it works very well since years. The only missing puzzle piece is the support for JPG/TIFF directy (without the manual deroute through Lightroom).

You see, it doesn't matter if those DNGs are larger than the JPG while having the same quality. They are only intermediaries to be fed into the Adobe DNG Converter in order to produce the preview.

That's why I was so excited to find your solution and though I'd reach out and ask if you would be willing to add that JPG/TIFF support. This would be such a game changer for me! Thanks again for considering.

Here are some sample files. If you need anything else, please let me know!
https://www.dropbox.com/s/ult1gd11jxtcq6h/DNG_from_JPG_TIFF.zip?dl=1

**Comment by iiborg** [comment]
For me, the reason not to convert TIFFs / JPEGs to dng is that it is impossible to know what were the edits, edits are rarely a simple gamma, and the resulting dng isn't even close to linear. Users are already very confused, why confuse them further?

**Comment by cytrinox** [comment]
@iiborg I've checked what Adobe does when converting JPEG to DNG. If the source image is sRGB or AdobeRGB (icc profile embedded), they pack the decompressed 8 bit data into DNG and assign the LinearizationTable tag to map the 8 bit data to 16 bit range. But the curve points are not linear, it's an inverse gamma function. The curves matches very close the inverse gamma function for 1.8, 2.2 or 2.4 - depending on original color space. The task to linearize data back is delayed to the reader of such DNGs. Only for other ICC profiles (like custom profiles) the data is linearized before writing to DNG, maybe they have some special logic for such cases.

**Comment by iiborg** [comment]
@cytrinox That's what I was trying to say, one can address the gamma, but not the unknown tonal curves applied along with the gamma. In certain cases, for out-of-camera files, after collecting a lot of samples and/or with the help of camera manufacturers, one can make a table of specific curves applied in the cameras; but even this extremely voluminous work doesn't cover TIFFs or those JPEGs that were edited.

**Comment by gwegner** [comment]
I think, 99% of all JPGs will be sRGB, 8bit. They are preprocessed files anyway. They could be converted to tiff and wrapped into the DNG container. This would help me tremendously for my application, as I elaborated above.

**Comment by gwegner** [comment]
Any chance you guys helping me with that?

**Comment by cytrinox** [comment]
I've an idea how implement something that may fit your requirements, as I sometimes need to construct a DNG from different inputs, like take the raw image from file A and exif data from file B. I agree with @iiborg that reverting back to plain linear raw is not well defined and could lead to invalid DNG files.

That's maybe the reason why Adobe has not ported their JPEG->DNG conversion process from Lightroom to DNG Converter. Inside Lightroom, they could handle whatever invalid file the software has created, but with DNG Converter, the file is usually processed in other applications, which could result in more support requests for Adobe regarding wrong colors in DNG files.

For me, that's a good reason to not implement this directly into the dnglab convert command. Even for sRGB data, it's not well defined how to convert back (of course, it would work in many cases).

But a more low level command that can address much more tasks would be nice to have. I was thinking about something like:

    dnglab makedng /tmp/my_photo.dng --raw-pixel-source inputfile1.CR2 --exif-source preview.jpg --xmp-source history.xmp --preview-source preview.jpg --color-matrix D65=1,2,3,4...

With such command, it would be possible to read regular images files like JPEG as pixel input, like:

    dnglab makedng /tmp/my_photo.dng --raw-pixel-source IMG_1234.jpg --dng-linearize-table 0,1,3,6,7,8...

Then you would have multiple options. If the process to revert to linear data is to simply specify a linearization table (the Lightroom solution for sRGB and AdobeRGB), then you can just specify whatever table data you want (maybe I can add some shortcuts like `--dng-linearize-table inverse-srgb-2.2`. If the image requires more processing, you have to prepare the image before calling dnglab. And of course, this command will not be able to process a batch of files, just one file per call.

**Comment by gwegner** [comment]
I would love to try this out!! If it works, I will definitely show my gratitude!

**Comment by gwegner** [comment]
I saw that the dropbox link doesn't work anymore. Let me know, if you need any test files or beta test assistance.

**Comment by gwegner** [comment]
@cytrinox any news on this?

**Comment by cytrinox** [comment]
That's a preview of makedng doc:
````
Usage: dnglab makedng [OPTIONS] --input <INPUT>...

Options:
  -d...                                 turns on debugging mode
  -o, --output <OUTPUT>                 Input files (raw, preview, exif, ...), index for map starts with 0
  -i, --input <INPUT>...                Source image for raw pixel (full resolution)
  -v                                    Print more messages
      --map <MAP>...                    Input usage map [default: 0:raw 0:preview 0:thumbnail 0:exif 0:xmp]
      --dng-version <VERSION>           DNG specification version [default: 1.6] [possible values: 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
      --dng-backward-version <VERSION>  DNG specification version [default: 1.4] [possible values: 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
      --matrix1 <MATRIX>                Matrix 1 [possible values: XYZ_sRGB_D50, XYZ_sRGB_D65, XYZ_sRGB_D55, XYZ_AdobeRGB_D50, "custom 3x3 matrix (comma seperated)"]
      --matrix2 <MATRIX>                Matrix 2 [possible values: XYZ_sRGB_D50, XYZ_sRGB_D65, XYZ_sRGB_D55, XYZ_AdobeRGB_D50, "custom 3x3 matrix (comma seperated)"]
      --matrix3 <MATRIX>                Matrix 3 [possible values: XYZ_sRGB_D50, XYZ_sRGB_D65, XYZ_sRGB_D55, XYZ_AdobeRGB_D50, "custom 3x3 matrix (comma seperated)"]
      --illuminant1 <ILLUMINANT>        Illuminant 1 [possible values: D50, D65]
      --illuminant2 <ILLUMINANT>        Illuminant 2 [possible values: D50, D65]
      --illuminant3 <ILLUMINANT>        Illuminant 3 [possible values: D50, D65]
      --linearization <TABLE>           Linearization table [possible values: sRGB_8bit_gamma2.0, sRGB_8bit_gamma2.2, sRGB_8bit_gamma2.4, sRGB_8bit_gamma2.0_invert, sRGB_8bit_gamma2.2_invert, sRGB_8bit_gamma2.4_invert, sRGB_16bit_gamma2.0, sRGB_16bit_gamma2.2, sRGB_16bit_gamma2.4, sRGB_16bit_gamma2.0_invert, sRGB_16bit_gamma2.2_invert, sRGB_16bit_gamma2.4_invert, "custom table (comma seperated)"]
      --wb <R,G,B>                      Whitebalance as-shot
      --white-xy <x,y>                  Whitebalance as-shot encoded as xy chromaticity coordinates [possible values: D50, D65, "custom x,y value (comma seperated)"]
  -f, --override                        Override existing files
  -h, --help                            Print help
````

Assuming that a given JPEG file has sRGB color profile based on D65 white point and gamma 2.2, it can be converted by:

````dnglab makedng -o /tmp/foo.dng --input example_jpeg_8bit_sRGB.jpg -f --white-xy D65 --linearization sRGB_8bit_gamma2.2_invert --matrix1 XYZ_sRGB_D65 --illuminant1 D65````

Results seems to be acceptable, code needs some cleanup but should be merged for upcoming 0.6 milestone.

**Comment by gwegner** [comment]
This sounds fantastic!
Let me know, if there is a beta that I could test.
Kind regard.
Gunther


Am Mo., 16. Okt. 2023 um 21:27 Uhr schrieb Daniel Vogelbacher <
***@***.***>:

**Comment by cytrinox** [comment]
A win32 artifact is available at https://github.com/dnglab/dnglab/actions/runs/6597883479#artifacts

**Comment by gwegner** [comment]
Today I tested DNGLab 0.6 with your JPG to DNG implementation and it looks promising! :-) Thank you for that!!

I first tested it under Windows and then also built a Mac universal version (ARM and Intel), both worked great. If you are interested, I can provide it to you or give you the steps on how to build it.

I did my tests with the command line you gave as an example:
`dnglab makedng -v -d -o output.DNG --input input.JPG -f --white-xy D65 --linearization sRGB_8bit_gamma2.4_invert --matrix1 XYZ_sRGB_D65 --illuminant1 D65`

Unfortunately I found a few things:

1. Something doesn't seem right with the color profile. Lightroom initially shows a version that is clearly too bright, then when you go into the Develop module it develops it, but then it becomes clearly too contrasty. Sometimes he then jumps back and forth between these versions. See screenshots that I've sent you via email.
2. If, for example, the input file is not found, it still creates a DNG file a few bytes long.
3. At the moment the preview is missing in the DNG. If possible, could you embed the original JPG into the DNG as a preview?
4. The DNGs are twice as large as if they were created with the Adobe DNG Converter. If you then send one of the DNGs from DNGLab through the Adobe Converter again, the size is halved.

If you don't have Lightroom Classic and don't want to download the trial version, you can also test it with the free Adobe DNG Converter, download it from: https://helpx.adobe.com/de/camera-raw/using/adobe-dng-converter.html

Then you send the DNG created by DNGLab through the Adobe DNG converter again, which then embeds a preview (this is then basically "developed" from the DNG via the Adobe Engine with neutral develop settings).
You can the have this preview written to a JPG with ExifTool and see the colors compared to the original:

`exiftool -b -previewimage -w preview.jpg input.dng`

Thank you very much for your effort and kind regards!

**Comment by cytrinox** [comment]
This feature was merged into master.
