### ISSUE TITLE
Unknown camera: make: "Canon", model: "Canon EOS R5 C", mode: "raw"

### ISSUE THREAD

**Issue by pierre1618** [dnglab/dnglab#299]
Hi, i got a problem when i"m trying to convert a CR3 file to DNG, the convertion failed and i got the error 
Unknown camera: make: "Canon", model: "Canon EOS R5 C", mode: "raw", this is strange because the camera "Canon EOS R5" are in the list of supported format (maybe the problem is because of the C).

version=dnglab 0.5.1

**Comment by lclevy** [comment]
These are different models

**Comment by cytrinox** [comment]
@pierre1618 Please provide a sample set of raw files: https://github.com/dnglab/dnglab/blob/main/CONTRIBUTE_SAMPLES.md#canon-cr3
It should be easy to add support for it.

**Comment by pierre1618** [comment]
I unfortunately don't have access to the camera directly but if someone has access to it that would be very nice !

**Comment by cytrinox** [comment]
duplicate of #297
