### ISSUE TITLE
Compression results in larger file size?!?

### ISSUE THREAD

**Issue by tonydiep** [dnglab/dnglab#300]
Using a 24M raw Sony ARW file:
  using --compression=lossless --embed-raw=false results in a 26M dng
  using --compression=none --embed-raw=false results in a 48M dng

Is the dng file supposed to be bigger than / 2X the raw file?

**Comment by cytrinox** [comment]
ARW is already compressed (and/or has reduced bit depth), so the process is to uncompress and recompress the data.
Some compression methods are good, others are better. DNG's LJPEG92 based compression is good.
For uncompressed DNG, the file is for sure bigger.
