### ISSUE TITLE
Publish rawler to crates.io

### ISSUE THREAD

**Issue by RReverser** [dnglab/dnglab#318]
I noticed the rawler library in this repository which sounds quite interesting for my needs and is already shaped as a separate crate, but it seems it hasn't been published to crates.io yet.

Are there any plans to do so?

**Comment by cytrinox** [comment]
Yes, but for now the crate API is not yet stable and my primary goal was to have a tool to convert CR3 to dng.
No timeline for stabilizing and publishing yet, sorry.

**Comment by RReverser** [comment]
> my primary goal was to have a tool to convert CR3 to dng

Yeah as mentioned in the linked issue on rawloader, that's the main thing I'm missing as well. I'm using rawler via git dependency in my Cargo.toml for now, but it would be nice if at least this format could be upstreamed to the original repo in a PR.

**Comment by RReverser** [comment]
Can you publish a new version please? https://github.com/dnglab/dnglab/commit/5c1fe998bd36e694c6e1e856a416808dfc5be4e8#diff-eb3c9f4af16d9a6a0f0d870fa5caf897feefec448e34b396bc7ee1bd7f6ef179 is something that would be very useful to have - I had to work around this by integrating mmap myself with some rather weird hacks I'd like to remove.
