### ISSUE TITLE
Support Sony Alpha 6700

### ISSUE THREAD

**Issue by pick2510** [dnglab/dnglab#325]
Hi, 
I just got my Sony A6700. Since this is a very similar camera based on the same sensor as the FX30, I just adapted created a new a6700.toml based on fx30.toml and it works flawless.

Is this all we need to add support? Or should I test some other scenarios?

**Comment by cytrinox** [comment]
Yeah, please create a PR and provide a link to raw samples so I can add these to the raw test suite. Thanks.

**Comment by pick2510** [comment]
Ok, great.
Do you need a full sample set or is one raw file enough?

**Comment by cytrinox** [comment]
Full sample set, for each supported mode (lossless, crops etc.) should exist a test case.

**Comment by pick2510** [comment]
Done. 
#326
