### ISSUE TITLE
2GB R7 raw burst gives 2GB file size for each DNG file

### ISSUE THREAD

**Issue by PeterWem** [dnglab/dnglab#345]
I downloaded raw burst from this one https://www.fredmiranda.com/forum/topic/1826640/1#16354876 and when I converted the 2GB CR3 file with DNGLab I got 85 DNG files. Total size 168GB.
Command:

`./dnglab_linux_x64 convert --image-index all RawBurstR7.CR3 /media/macgyver/18TB/Radera/roll.dng`

**Comment by phototrek** [comment]
Yeah, that's my burst that I shared with FM. The other problem is that it took my M2Ultra MacStudio 44 minutes to perform the operation:

Converted 85/85 files
Total time: 2656.74s
/Users/stan/Build/dnglab/target/release/dnglab convert --image-index all    60217.77s user 816.67s system 2296% cpu 44:17.27 total

I built dnglab from source on my Mac.

**Comment by cytrinox** [comment]
Use --embed-raw false as argument.

Am 1. Oktober 2023 11:43:06 MESZ schrieb PeterWem ***@***.***>:

**Comment by PeterWem** [comment]
Thanks! Much better. Took 19,7 seconds to extract 85 dng files.
