### ISSUE TITLE
Support for Panasonic Lumix S5II (DC-S5M2)

### ISSUE THREAD

**Issue by brettalcox** [dnglab/dnglab#355]
Make: Panasonic 
Model: DC-S5M2
Samples: https://github.com/brettalcox/dc-s5m2-samples (4:3, 3:2, 1:1, 16:9, 65:24, 2:1 @ ISO100)

**Comment by cytrinox** [comment]
See also #177

**Comment by cytrinox** [comment]
fixed in v0.6.1
