### ISSUE TITLE
Unknown camera: make: "SONY", model: "ILCE-7CM2", mode: ""

### ISSUE THREAD

**Issue by ah-its-andy** [dnglab/dnglab#357]
[ERROR ][dnglab::jobs::raw2dng] Unsupported file: "_DSC0021.ARW"
Unknown camera: make: "SONY", model: "ILCE-7CM2", mode: ""
Please report this issue at 'https://github.com/dnglab/dnglab/issues'! (bin/dnglab/src/jobs/raw2dng.rs:82)
Status: Failed: '/home/andrew/source/dnglab/_DSC0021.ARW', File is unsupported: Unknown camera, model "ILCE-7CM2", make: "SONY", mode: ""
Converted 0/1 files, 1 failed:
   /home/andrew/source/dnglab/_DSC0021.ARW
Total time: 0.04s

**Comment by cytrinox** [comment]
Please provide samples for this camera model: https://github.com/dnglab/dnglab/blob/main/CONTRIBUTE_SAMPLES.md
