### ISSUE TITLE
rawler: access all EXIF tags of a raw file

### ISSUE THREAD

**Issue by RReverser** [dnglab/dnglab#400]
I'm parsing CR3 files and, among others, need to extract `FocalPlaneYResolution`.

When I parse it using `decode_file(...)`, the `dng_tags` field remains unpopulated - I guess it's format-dependant and is only filled for DNG images.

So then I found I can retrieve global decoder and invoke `raw_metadata(...)` on the file, which is more cumbersome, but at least actually parses the metadata from CR3. Unfortunately, the returned metadata is limited to only some well-known fields and doesn't contain what I need.

Is there any way to get raw list of all tags instead, so that I could extract what I need by EXIF number myself? Maybe `dng_tags` could be populated for any format upon decoding?

**Comment by cytrinox** [comment]
Access to raw IFDs is problematic, as in newer formats like CR3 there is no "root IFD". In CR3, EXIF tags are spread over CMT1, CMT2 and CMT3 boxes, each forming a separate root IFD.

The recommended solution is to just extend all tags defined by EXIF standard here: https://github.com/dnglab/dnglab/blob/7f6ee5a67ef522e30f2c7cb5bc1634696e6e44de/rawler/src/exif.rs#L160
Then the requested EXIF attribute can be simply accessed via raw_metadata().

I would be happy reviewing a PR for this :wink:

**Comment by RReverser** [comment]
> Access to raw IFDs is problematic, as in newer formats like CR3 there is no "root IFD". In CR3, EXIF tags are spread over CMT1, CMT2 and CMT3 boxes, each forming a separate root IFD.

Yeah I don't need raw IFDs, just raw EXIF values, even if it's after merging all EXIF data from all IFDs.

That in, in the linked branch it could collect any unknown values into a separate `HashMap<u16, Value>`. That doesn't solve the issue of not getting this info right in `dng_tags` upon `decode_image`, but at least provides some way to access the data.

**Comment by cytrinox** [comment]
This should be possible now as IFDs are now accessible #412

**Comment by RReverser** [comment]
@cytrinox To be honest, I'm still a bit confused on how to use it. Maybe it's a bit _too_ low-level now?

Ideally, I just want to get the same structure as provided by https://docs.rs/kamadak-exif/latest/exif/ so that I could handle any raw images in the same way I can only handle any regular images (e.g. JPEG), with same data types.

Right now I have to achieve that, I have to reparse same source twice - using rawler and using kamadak-exif - which kinda works, but is both inefficient and also worrying because kamadak-exif says it can only read TIFF-based raw formats.

I'd like to avoid that reparsing, but I don't see how.

**Comment by RReverser** [comment]
Ah

> Decoder::ifd() is implemented only for DNG decoder yet but it's easy
to extend it to all other decoders.

This also seems to be a problem... I guess I'll have to stick with reparsing for now.
