### ISSUE TITLE
Improve memory buffering

### ISSUE THREAD

**Issue by RReverser** [dnglab/dnglab#401]
I'm using mmap-ed RAW files as the source of data, which should provide best performance as all the data is directly mapped into memory and accessible just `&[u8]`.

Unfortunately, rawler can't benefit from this yet, because 1) RawFile requires only `&'static` data, which can be worked around by giving it a custom newtype that preserves the mmap handle, but is somewhat cumbersome and 2) rawler does a lot of tiny allocations & copying in methods like `subview`, which are unnecessarily expensive, as with sources like Mmap or even just Vec<u8> it could instead use subslices from existing memory.

In particular, each `subview_until_eof` copies almost the entire file into new and new allocations over and over. At that point it would be cheaper to have one central `Vec<u8>` and use `&[u8]` subslices everywhere.

**Comment by RReverser** [comment]
After thinking about this a bit more, I think the best solution here would be to use the common `bytes` crate: https://docs.rs/bytes/latest/bytes/struct.Bytes.html

It allows to wrap arbitrary buffer types, provides zero-cost shared chunks without the lifetime mess, as well as provides some useful parsing helpers.

**Comment by cytrinox** [comment]
May have a look at #416, feedback welcome.

**Comment by RReverser** [comment]
Sorry, I somehow missed that comment in the past, but #416 (now merged) looks very promising. Can't wait to try it out once it's published to crates.io, but closing this issue for now.
