### ISSUE TITLE
Specify Output Bit Depth

### ISSUE THREAD

**Issue by jedypod** [dnglab/dnglab#417]
Spinning off an issue from my [deranged rambling](https://github.com/dnglab/dnglab/issues/368#issuecomment-1985025669) in #368, I was wondering if it might be a possibility to specify the bit depth of the output DNG image? The sensible default I assume would be to keep the bit depth of the input image data unchanged. This does seem to be the case when compression is enabled, but does not seem to be the case when the output dng is uncompressed (12 bit dngs are up-sampled to 16 bit for example). 

I could definitely see a case where being able to specify the output bit depth could be useful though. Would this feature be a possibility?

Thanks for considering it!

**Comment by cytrinox** [comment]
As lossless compression in DNG is widely supported, I'v not implemented any optimization for uncompressed output. Do you have a usecase where lossless compression is unusable for you?

**Comment by jedypod** [comment]
I don't really have a use-case where I would want to be outputting uncompressed dngs. If I did though, it currently would be unusable because the bit depth is being resampled to 16bit from whatever the source is (most cinema dngs i have are 12bit, most stills are 14bit).

So I guess my rambling post above is twofold:

1. A bug report for the above
2. A request to specify the output bit depth. This _would_ actually be quite useful for me I think. Taking a 12bit uncompressed dng source and re-encoding to 10bit dng with lj92 compression as 10bit with a nonlinear transfer function would be very useful. Currently I don't believe that is possible with dnglab?

Hopefully that clarifies things.

**Comment by kmilos** [comment]
> If I did though, it currently would be unusable because the bit depth is being resampled to 16bit from whatever the source is (most cinema dngs i have are 12bit, most stills are 14bit).

> A bug report for the above

This is not a bug, but how it works. Uncompressed samples >8b must be stored as at least exactly 2 bytes (16bits). They are not "resampled" in any way, just have to be stored that way (LSB aligned with some MSBs wasted/zeroes). One could do some bit packing when this is no longer true, but this is not mandatory.

It's the WhiteLevel tag that determines the actual bit depth of the sample.

I'm pretty sure such files work ok w/ any Adobe SW, LibRaw-based SW (e.g. ART, rawpy, etc.), and RawSpeed-based SW (e.g. darktable), or vkdt using rawler. For any other apps not working with these uncompressed files, there should be a bug filed with them.

**Comment by cytrinox** [comment]
If lossless compression is selected, output bit depth is usually matches source bit depth (with few exceptions).
For uncompressed output, dnglab only supports 16 bit unpacked data for now. 

Bit depth may change if source contains a linearization table - as linearization is applied during decoding process.
