### ISSUE TITLE
 Unknown camera, model 'SP570UZ'; 'DMC-FX150'

### ISSUE THREAD

**Issue by abpolly** [dnglab/dnglab#420]
Hi, these two cameras are about 15 years old, but still took good pictures.
Thank you

./dnglab_linux_x64 convert P7048098.ORF P7048098.dng
[ERROR ][dnglab_lib::jobs::raw2dng] Unsupported file: "P7048098.ORF"
File is unsupported: Unknown camera, model 'SP570UZ', make: 'OLYMPUS IMAGING CORP.', mode: ''
Please report this issue at 'https://github.com/dnglab/dnglab/issues'!
(bin/dnglab/dnglab-lib/src/jobs/raw2dng.rs:82)

./dnglab_linux_x64 convert P1010249.RW2 P1010249.dng
[ERROR ][dnglab_lib::jobs::raw2dng] Unsupported file: "P1010249.RW2"
File is unsupported: Unknown camera, model 'DMC-FX150', make: 'Panasonic', mode: '4:3'
Please report this issue at 'https://github.com/dnglab/dnglab/issues'!
(bin/dnglab/dnglab-lib/src/jobs/raw2dng.rs:82)

**Comment by cytrinox** [comment]
Please contribute samples for these cameras: https://github.com/dnglab/dnglab/blob/main/CONTRIBUTE_SAMPLES.md

**Comment by abpolly** [comment]
Here are links to download samples
Olympus-SP-570UZ
https://drive.google.com/file/d/1ROFczXkjkojjzNCIy9HttXK1HId3g2g5/view?usp=sharing

Panasonic-DMC-FX150
https://drive.google.com/file/d/1HWJTvsDPlmZQo8xQ1nM5o2amB2ZxKD8t/view?usp=sharing

**Comment by cytrinox** [comment]
@kmilos FYI. DMC-FX150 is missing in rawspeed, too.

**Comment by cytrinox** [comment]
@abpolly Is 4:3 the only aspect ratio DMC-FX150 supports? No 1:1, 3:2, 16:9?

**Comment by kmilos** [comment]
Thanks - the user did open an issue for dt/RawSpeed as well, so kudos for that!

We are, however stuck waiting for the full set of aspect ratios from the same shoot.

**Comment by abpolly** [comment]
Hi,
I'll try to take photos with different ratios. It's overcast now, hopefully in a day or two there will be sun and clouds. Thank you.
