### ISSUE TITLE
不支持佳能R8

### ISSUE THREAD

**Issue by zhujianghai** [dnglab/dnglab#432]
[ERROR ][dnglab_lib::jobs::raw2dng] Unsupported file: "IMG_3493.CR3"
File is unsupported: Unknown camera, model 'Canon EOS R8', make: 'Canon', mode: 'craw'
Please report this issue at 'https://github.com/dnglab/dnglab/issues'! (bin\dnglab\dnglab-lib\src\jobs\raw2dng.rs:82)
Converted 0/1 files, 1 failed:
   \\?\E:\JH\RAW Convert EMOMOD v1.2\Raw\IMG_3493.CR3
Total time: 0.21s
No matching files

E:\JH\RAW Convert EMOMOD v1.2>

**Comment by wdcodecn** [comment]
可以先用 exiftoolgui 把 Model 修改为 Canon EOS R6 型号即可

**Comment by samuelliuliuliu666** [comment]
[ERROR ][dnglab_lib::jobs::raw2dng] Unsupported file: "IMG_3229.CR3"
File is unsupported: Unknown camera, model 'Canon EOS R8', make: 'Canon', mode: 'raw'
Please report this issue at 'https://github.com/dnglab/dnglab/issues'! (bin/dnglab/dnglab-lib/src/jobs/raw2dng.rs:82)
Converted 0/1 files, 1 failed:
   /Users/mac/Desktop/Raw Convert/Raw/IMG_3229.CR3
Total time: 0.03s
Error: File not found - /Users/mac/Desktop/Raw Convert/Convert/Fujifilm/*.dng
    0 image files updated
    1 files weren't updated due to errors
rm: /Users/mac/Desktop/Raw Convert/Convert/Fujifilm/*.dng_original: No such file or directory
/Users/mac/Desktop/Raw Convert/FujifilmConvert.command: line 5: exit: 0；: numeric argument required
logout

**same problem. Does exiftoolgui has support on Mac OS? I only find win64 version.**

**Comment by carsongmiller** [comment]
if you change the exif data for the camera model of the image from "Canon EOS R8" to "Canon EOS R6m2", it works.  You can use [EXIFTool ](https://exiftool.org/) to do that.

exiftool -model='Canon EOS R6m2" <image path>

**Comment by cytrinox** [comment]
fixed with #441
