### ISSUE TITLE
Panasonic DMC-FX150 - uploaded samples to https://raw.pixls.us/. Three aspect ratios.

### ISSUE THREAD

**Issue by abpolly** [dnglab/dnglab#434]
Panasonic DMC-FX150 - uploaded samples to https://raw.pixls.us/. Three aspect ratios. There is no obvious indication that the file has been uploaded, so, just in case, here is a link to download it.
https://drive.google.com/file/d/1samj8PxLi5-p3d1GJYEys1pU13JVi1LW/view?usp=drive_link

**Comment by cytrinox** [comment]
fixed in v0.6.1
