### ISSUE TITLE
Canon RAW Burst Mode extraction not working

### ISSUE THREAD

**Issue by carsongmiller** [dnglab/dnglab#442]
Creating a new issue branching off of my original one that mentioned this issue  (#440)

Extracting images from canon CR3 files that contain a "roll" of images captured using canon's RAW burst mode do not get extracted correctly when using the command:

./dnglab convert --image-index all --embed-raw false ./images/CSI_0157.CR3 ./images/roll

I've tested using a raw image roll from both an R8 and R7, same results.  I've also tested both on Windows and in Linux via WSL (Ubuntu).  This testing was done _after_ #441 

The tool does extract the correct number of images (11 in my case) and create 11 new DNG's, but they are all the same image--the first image in the roll.

Sample Raw Burst mode file from an R8 [here](https://drive.google.com/file/d/1t-K28ddFx3j5bYGzOkX1MvalBFo2I9-m/view?usp=sharing)

**Comment by cytrinox** [comment]
Can not reproduce it with my R7 test sample. Hint: The thumbnail and jpeg preview is always the scene from first frame, as in CR3 there is only one single thumbnail and preview even if multiple frames recorded.

**Comment by cytrinox** [comment]
As I don't have a R8 roll file sample, would be happy to get a sample under CC license for integration into test suite.

**Comment by carsongmiller** [comment]
Your hint gave me the answer.  I didn't realize that!  I even tried importing into lightroom, but as soon as I saw the thumbnails in lightroom and they were still the same, I quit that.  I guess I never actually looked at the images in a way that _actually_ read the RAW image data.  The latest build is indeed working with my R8 images.  Thanks for the help
