### ISSUE TITLE
Sony ARW file convert failed with lens warning.

### ISSUE THREAD

**Issue by Adrian-Grimm** [dnglab/dnglab#450]
### Description

Compiled and tested on macOS 14.5. - builded from Main [828ea44]:(https://github.com/dnglab/dnglab/commit/828ea4485ed2128d082fd5459db592473ba84ee7)

Pictures tested to convert but failed - Affinity Photo is able to show the file with black boarders, but Photomater can't.

Gamera: Sony-a7CM2
Lens: Sony FE 28-60 4-5.6

### Log

[WARN  ][rawler::lens] Unable to find lens definition. Please open an issue at https://github.com/dnglab/dnglab/issues and provide the RAW file. (rawler/src/lens.rs:188)

### Source and Result files

- Sony-a7CM2-FE28-60-4-5.6-DNG.zip: https://d.pr/f/pnXFOe

**Comment by qdwang** [comment]
same issue here. And there are some issues:
1. The converted dng file is larger(57.5 mb) than the original uncompressed ARW file(49 mb).
2. The converted dng cannot be open by the MacOS Preview App. It just pops out the error msg: `The file xxx could not be opened`.

**Comment by cytrinox** [comment]
Can't reproduce any of the problems (checked with darktable and geeqie for preview). Metadata looks also fine to me.
DNG is 40 MiB vs. 48 MiB ARW.

Warning for missing lens info is what it says - just a warning. I'll add the lens definition to the lens database, but this warning is unrelated to any of the problems described here.

Hint: Black borders are visible when editing app has no support for DefaultCropSize and DefaultCropOrigin DNG tags.

**Comment by Adrian-Grimm** [comment]
@cytrinox 
At least on macOS those files does not preview and seems kind of broken.
The dnglab tool itself works and this also quite a lot faster compared to "adobe DNG Converter.app" - but that one produces perfect compatible DNG files.
The same sample file processed with Adobe's converter is resulting in this one: https://d.pr/f/MjaU2m e.g. that worked with preview, Photometer, Affinity Photo 2 and others.

The lens warning is kind of strange because `dnglab lenses` shows this line included:

`e-mount    Sony               FE 28-60mm F4-5.6`

Which should be exactly the used lens.

**Comment by Adrian-Grimm** [comment]
Version 6.2 fixed all issues 👍🏻 thx. I really like this tool already!
Everything is running fast and stable on MacOS ARM64 - only a verifiable signed build would may help others...
