### ISSUE TITLE
Unknown camera, model 'iXM-GS120'

### ISSUE THREAD

**Issue by suchb** [dnglab/dnglab#459]
[ERROR ][dnglab_lib::jobs::raw2dng] Unsupported file: "P0452274.IIQ"
File is unsupported: Unknown camera, model 'iXM-GS120', make: 'Phase One', mode: ''
Please report this issue at 'https://github.com/dnglab/dnglab/issues'! (bin/dnglab/dnglab-lib/src/jobs/raw2dng.rs:82)
Converted 0/1 files, 1 failed:
   /home/suchb/imagesdk-test/suchb-test/P0452274.IIQ
Total time: 0.49s

**Comment by cytrinox** [comment]
Raw samples required to implement support for this camera. Please upload a set of RAW files licensed under CC0 - see https://github.com/dnglab/dnglab/blob/main/CONTRIBUTE_SAMPLES.md for details.

**Comment by cytrinox** [comment]
No samples provided so far, feel free to reopen the issue if you can provide the requested samples.
