### ISSUE TITLE
Is it (theoretically) possible to convert one RAW format to another?

### ISSUE THREAD

**Issue by ArcheyChen** [dnglab/dnglab#464]
We know that Fuji cameras have their own exclusive filters, and Canon has done a good job in optimizing the color of portraits.

and they both offer official software to convert RAW to jpg on PC.

I wonder if we can "fake" the raw file, like taking a photo using Sony a7r2, and convert it's raw file to cr2, then we can use Canon DPP to add Canon's special optimization to the photo.

is that possible?

**Comment by cytrinox** [comment]
Yes, but there are many problems like faking the camera model name, so DPP would open the file. DPP would apply the color matrix for the faked model which produces wrong colors. 
While there may workarounds for all the little problems, it's not worth the work and out of scope of dnglab.
