### ISSUE TITLE
`CameraModelName` EXIF tag value does not match *Adobe DNG Converter* or original CR2 file value.

### ISSUE THREAD

**Issue by KelSolaar** [dnglab/dnglab#465]
Hello,

I noticed that the `CameraModelName` EXIF tag does not have the same value as that given by **Adobe DNG Converter** or the original CR2 for my 5D Mark II:

**dnglab**

```
Make                            : Canon
Camera Model Name               : EOS 5D Mark II
```

**Adobe DNG Converter**

```
Make                            : Canon
Camera Model Name               : Canon EOS 5D Mark II
```

The CR2 EXIF data is as follows:

```
Make                            : Canon
Camera Model Name               : Canon EOS 5D Mark II
```

This might seem benign but it breaks any automated lookups in databases. For example, Lensfun does primarily [reference the camera](https://github.com/lensfun/lensfun/blob/db4db53f4e89b46845ecfdc3d61a150018035ab4/data/db/slr-canon.xml#L95) using the **Adobe DNG Converter** / CR2 name:

```xml
    <camera>
        <maker>Canon</maker>
        <model>Canon EOS 5D Mark II</model>
        <model lang="en">EOS 5D Mark II</model>
        <mount>Canon EF</mount>
        <cropfactor>1</cropfactor>
    </camera>
```

Cheers.

Thomas

**Comment by KelSolaar** [comment]
Testing with a Nikon file, the behaviour seems to be the same:

```
exiftool DSC_2681.NEF | grep "Camera Model"
Camera Model Name               : NIKON Z 9
```

```
exiftool DSC_2681.dng | grep "Camera Model"
Camera Model Name               : Z 9
Unique Camera Model             : Nikon Z 9
```

**Comment by cytrinox** [comment]
This is expected behavior. For unknown reason, Adobe prefixes the model with the maker name.
For cameras with DNG support, the naming scheme is (often):
````
Make                            : Google
Camera Model Name               : Pixel 2 XL
---
Make                            : Leica Camera AG
Camera Model Name               : M9 Digital Camera
````

Apart from that, I use lensfun a lot inside darktable with Canon and Fujifilm cameras and never had issues with camera/lens lookups.

**Comment by KelSolaar** [comment]
Hello,

It is not necessarily Adobe but the camera makers. If you look at my second comment both the original Canon CR2 and the Nikon NEF file have the make prepended to the tag, I haven't looked at your codebase but it seems like something is changing that tag in dnglab.

Cheers,

Thomas

**Comment by cytrinox** [comment]
dnglab always follows the paradigm to skip maker name in model name - for camera model and lens model. All make/model values are taken from camera/lens catalog instead reading them from raw files (except for Fujifilm lenses where all information exists already in RAF format so lens database would be duplicate work).

**Comment by KelSolaar** [comment]
Thanks for the clarification!

This is really important information that should probably be written somewhere in the README/documentation as it was unexpected to see the EXIF data modified in such way and not passed as is. Are there other tags that you are passing but modifying? A list would be greatly appreciated!

From a pipeline standpoint, it means that we need to have special code for dnglab, not a big deal in the aforementioned case and the benefit of having a Linux CLI tool outweighs the minor inconvenience.

Cheers,
