### ISSUE TITLE
File is unsupported: Unknown camera, model 'ZV-E10M2', make: 'SONY', mode: ''

### ISSUE THREAD

**Issue by ixsiid** [dnglab/dnglab#467]
It newly launched on August 2.
https://www.sony.jp/ichigan/products/ZV-E10M2

It have two raw format "loss less compression" and "compression"
It don't have "no compression"

**Comment by ixsiid** [comment]
I took samples of the following combinations

- RAW format [lossless compression, compression]
- Image format [Jpe, HEIF(4:2:0), HEIF(4:2:2)]
- Image quality [X.FINE, FINE, STD, LIGHT]

24 ways in total.

How can I send you a sample?

**Comment by cytrinox** [comment]
Please follow https://github.com/dnglab/dnglab/blob/main/CONTRIBUTE_SAMPLES.md and upload the images to a transfer service, for example www.wetransfer.com

**Comment by ixsiid** [comment]
Please get from here
https://we.tl/t-FLiKKTGUs8
