### ISSUE TITLE
Add support for Apple Quicktake qtk files

### ISSUE THREAD

**Issue by giovariot** [dnglab/dnglab#483]
Hello, since the old Apple Quicktake files cannot be opened with modern editors it would be nice to be able to convert them to the dng format. 

I don't know if it would be possible to add that format, but it is currently fully supported by libraw and dcraw and supported when using the raw:filename.qtk parameter with imagemagick's convert command.

Here is a samples archive of images coming from a QuickTake 100
https://we.tl/t-lVi5Qqg36r

Thanks in advance!

**Comment by cytrinox** [comment]
@giovariot Link is dead, please upload again, thanks.

**Comment by giovariot** [comment]
[Here](http://down.dandu.be/QuickTake.zip) is a more better archive than mine, composed of files coming from the Apple QuickTake 100 and 150. I won't reupload mine as there were some old photos of me and my parents and I think this archive is better.

The camera files were, as far as I know, saved as .QTK files on Windows and PICT files on Macintosh.
