### ISSUE TITLE
Unknown lens model: 'EF50mm f/1.8 STM'.

### ISSUE THREAD

**Issue by nauotit** [dnglab/dnglab#57]
Hi, I'm using the Canon 90D with mainly two lens: the canon EF 50mm F1.8 and the canon EF 85mm F1.8.
I got the error message "Unknown lens model: 'EF50mm f/1.8 STM'. Please open an issue at https://github.com/dnglab/dnglab/issues and provide the RAW file".
I will provide as well shot with the EF 85mm F1.8 if I get the same issue.
Thanks a lot for your work, program is great and hugely usefull while waiting for native CR3 support in darktable.

I got a github error saying that the CR3 format is not supported, how can I give you the .CR3 files ?
I try to ZIP the CR3 file but got the error "is not included in the list".

Best regard,

**Comment by cytrinox** [comment]
Just post the lines containing the unknown lens model. This should be enough info to derive the correct lensdb entry.

**Comment by nauotit** [comment]
Thanks, here it is:
Unknown lens model: 'EF50mm f/1.8 STM'. Please open an issue at https://github.com/dnglab/dnglab/issues and provide the RAW file'
