### ISSUE TITLE
Unknown lens model: 'SAMYANG RF 14mm F2.8'. 

### ISSUE THREAD

**Issue by steve-pingpong** [dnglab/dnglab#58]
[014A5860.CR3.tar.gz](https://github.com/dnglab/dnglab/files/7166870/014A5860.CR3.tar.gz)
Unknown lens model: 'SAMYANG RF 14mm F2.8'.

**Comment by cytrinox** [comment]
@steve-pingpong This lens is unknown in exiftool, too. I would recommend to open an issue on https://github.com/exiftool/exiftool so they can add the lens there, too. In most cases I use the model name that is used in exiftool.
Seems the official name is **AF 14/2.8 RF** which I've used in dnglab now.
