### ISSUE TITLE
Feature request: wavelet / VC5 compression like GPR

### ISSUE THREAD

**Issue by embeeweezer** [dnglab/dnglab#75]
Great to see all the improvements to the recent releases! Not sure if this is the right place to ask for a feature request or even just sharing possible projects of interest.
Since I stumbled upon Gopro's GPR files with wavelet (VC5) compression (https://github.com/OgreTransporter/gpr via https://github.com/gopro/gpr) I wondered if this might be useful to the dnglab project. Having wavelet compressed CR3 files would be awesome!

**Comment by cytrinox** [comment]
CR3 uses wavelet based compression in CRAW mode, and dnglab is able to decode these files. :thinking:
