### ISSUE TITLE
Sample files used by the tests

### ISSUE THREAD

**Issue by markreidvfx** [dnglab/dnglab#76]
Are the sample files used by the tests available somewhere?

**Comment by cytrinox** [comment]
Not yet, it's very large. I already have webspace for it where the data should be published and at gitlab-ci runner should auto-test PRs against the data. It's just on my todo list :smile:

**Comment by cytrinox** [comment]
The sample files are now online: https://git.dnglab.org/?p=dnglab-testdata.git;a=summary

**Comment by markreidvfx** [comment]
Amazing! Thanks!
