### ISSUE TITLE
Add support for Canon PowerShot SX70 HS

### ISSUE THREAD

**Issue by jeaye** [dnglab/dnglab#77]
Hello! Thank you so much for this tool! I was really excited to see a way I might be able to bring these CR3 files into Darktable on GNU/Linux, but it seems that dnglab doesn't quite support the camera which created the files. What's involved in adding support for different versions of the PowerShot cameras, and more specifically the SX70 HS?

I'd be happy to help, if you can provide some guidance.

Worth noting, I've verified that https://raw.pixls.us/ has images for this camera. If more are needed, I can provide them.

### Output from running
```
~/projects/third-party/dnglab on main at 18:08:04 
❯ ./target/release/dnglab convert ~/sharebox/IMG_0694.CR3 test.dng
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: DecoderFail("File is unsupported: Couldn't find camera \"Canon\" \"Canon PowerShot SX70 HS\" mode \"\".\nPlease submit samples at https://raw.pixls.us/")', bin/dnglab/src/dnggen.rs:96:78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', bin/dnglab/src/dnggen.rs:100:4
```

**Comment by cytrinox** [comment]
CR3 is very complex and I need more samples than requested by raw.pixls.us.
It should be very easy to integrate SX70 HS support. Please read https://discuss.pixls.us/t/call-for-extended-cr3-samples-all-iso-combinations-needed/24959
You can zip and upload the whole samples to something like wetransfer.com and post the link here.
Please read carefully your camera manual, as I need samples for every (!) ISO setting and some high or low ISO settings sometimes hidden behind some extra options in the camera menu. These modes often named like H1 or H1 or L ISO.

**Comment by jeaye** [comment]
Oh, perfect. I'll follow these steps and get you everything you need. Thank you!

**Comment by cytrinox** [comment]
@jeaye I want to release 0.3.1 in the next days. Should this issue be keept on the 0.3.1 milestone?

**Comment by jeaye** [comment]
That'd be great. I plan on getting all of those photos to you by end of day tomorrow (Pacific Time), if that can work for you.

**Comment by jeaye** [comment]
I'm a day late! My apologies. Here's a zip with everything: https://upload.jeaye.com/tmp/canon_powershot_sx70_hs.zip (this link will expire in a few days)

Note that this camera doesn't have a low 50 ISO mode. Also, it doesn't have any 1.6x cropping feature. I've verified this in the manual, which is available here: https://www.manualslib.com/manual/1586387/Canon-Powershot-Sx70-Hs.html

If there's anything more that you need, or if anything is incorrect, please let me know and I'll get it sorted. I'm more available now, due to the holidays.

**Comment by cytrinox** [comment]
Thanks! Looks good.

**Comment by jeaye** [comment]
Thanks so much for adding this support! I was able to build from main, convert a CR3 into a DNG, and load it into Darktable, so think everything's working well. :grinning:
