### ISSUE TITLE
Canon CRM test media

### ISSUE THREAD

**Issue by markreidvfx** [dnglab/dnglab#97]
Hi,
I shot this batch of Canon R5 test media to help add Canon CRM support to [libraw](https://github.com/LibRaw/LibRaw/pull/446)

dnglab is welcome to use them if it wants :)

https://www.dropbox.com/sh/ty32q952xdzv3no/AAAIw1t7-ZRqH3TrpQoBfavMa?dl=0

If the files are too big for regression testing, Canon DPP and be used to extract single raw frames and create smaller CRM files.

**Comment by cytrinox** [comment]
@markreidvfx Thanks for the set. I own a R5 too but was not aware that CRM was a supported format of the R5 (I don't do anything with video). I've read your PR for libraw, can you give me a quick summarize for the CRM format? I've ignored it mostly because I thought it is not useful for image processing. But I assume it is possible to extract single frames from CRM?

It looks like your PR did not touch the decompressor code, so I assume CRM uses encoding type 3 which is already used for G5/G7 filmrolls?

I've added filmroll support to dnglab some time ago and you can select a specific image index when converting the filmroll to DNG. Can this be useful for CRM, too? I wonder what a possible image proeceddings workflow for CRM looks like.

**Comment by markreidvfx** [comment]
Yes it's type 3 and pretty much the same as frame roll. There is a small changes to the decoder. There are some extra bits in the CMP1 Atom that indicate to use a different median value in the decoder.  It should be able to be rolled into the frameroll support if you choose to add support. That's how it's currently being added to libraw. 

As for workflows using it, in the past I've used DNG sequences before in editing, but something like Resolve already has CRM support.

**Comment by cytrinox** [comment]
I've implemented CRM support today and shoot some test videos.
> No I think its needed. Each frame has different makenote samples, things like focal length, focal distance can change. Personally that is data I use for my applications.

This makes sense but there is only a single CTMD box per file (in trak 4). How is a single sample connected to different metadata information?

**Comment by cytrinox** [comment]
Do you know an attribute to detect if it is StandardRaw or LightRaw?

**Comment by markreidvfx** [comment]
I'm working on a patch for that, Quality in the camera settings tag is what DPP seems to uses
https://exiftool.org/TagNames/Canon.html#CameraSettings

https://github.com/markreidvfx/LibRaw/commit/20d9fb1de7fb071240a06fb8410c957fadb0ba7f

**Comment by cytrinox** [comment]
```
[DEBUG ][rawler::decoders::cr3] Canon quality mode: StandardRaw (rawler/src/decoders/cr3.rs:410)
[DEBUG ][rawler::decoders::cr3] Canon CLog mode: CLog3 (rawler/src/decoders/cr3.rs:421)
```

Awesome, thanks!

**Comment by markreidvfx** [comment]
There are a few more tags I've identified
https://github.com/markreidvfx/LibRaw/commit/b26a613d94bfc51bfb60b13c7b098c951ba985f6

But they don't effect the encoded data as far as I can tell, and aren't needed to develop the image

**Comment by cytrinox** [comment]
Seems like you should report these information to exiftool so Phil can add them :smile: 

Maybe you have already investigated into this:
Is any color conversion required? I see your note that for LightRaw, the WB coeffs are already baked in, so for DNG I must reverse this step. And for videos with for example BT.2020, the standard R5 D65 color matrix is wrong, too. The image only looks correct in Darktable if I choose Linear BT.2020 as input profile instead of the DNG embedded matrix. No idea if it is possible to embed a BT.2020 matrix into DNG...

**Comment by markreidvfx** [comment]
> I've implemented CRM support today and shoot some test videos.
> 
> > No I think its needed. Each frame has different makenote samples, things like focal length, focal distance can change. Personally that is data I use for my applications.
> 
> This makes sense but there is only a single CTMD box per file (in trak 4). How is a single sample connected to different metadata information?

The CTMD box doesn't actually contain the timed metadata. The track itself on contains the various sstc/stsz/co64 atoms needed to find the matching frames data.  There seems to be some data on CTMD atom, not really sure what it is.

**Comment by markreidvfx** [comment]
> Seems like you should report these information to exiftool so Phil can add them 😄
> 
> Maybe you have already investigated into this: Is any color conversion required? I see your note that for LightRaw, the WB coeffs are already baked in, so for DNG I must reverse this step. And for videos with for example BT.2020, the standard R5 D65 color matrix is wrong, too. The image only looks correct in Darktable if I choose Linear BT.2020 as input profile instead of the DNG embedded matrix. No idea if it is possible to embed a BT.2020 matrix into DNG...

not really sure yet, from what I've gathered so far the data seems to be in the same colorspace as regular CR3s.  which would make sense to me. When canonlog is on though the data is darker, I think it scaled down to fit the extra dynamic range into the data range. 

I've only messed a bit around with darktable.  If you set it to the input profile to linear BT.2020, that's the equivalent of doing no conversion, because it matching the working colorspace.   I did try with darktable to switch it to my custom libraw, but its unable to detect the camera model is unable to use the `standard color matrix` because exiv2 doesn't read CRM files fully either.

**Comment by cytrinox** [comment]
> 
> The CTMD box doesn't actually contain the timed metadata. The track itself on contains the various sstc/stsz/co64 atoms needed to find the matching frames data. There seems to be some data on CTMD atom, not really sure what it is.

![grafik](https://user-images.githubusercontent.com/509535/151691847-60ed0dcf-e515-4bc7-8597-03963e78bbc2.png)

Good hint, I've looked only at the **stsd** and CTMD box. :+1:

**Comment by cytrinox** [comment]
The whitelevel in makernotes is reported as ~14000 but the images are very dark. It seems a good value is `(1 << 12) - 1`. The sRGB videos are "okay" (a litte bit too bright) but the others are still too dark. Have you found another, better whitelevel? 
I assume the sRGB files are shoot with setting "Canon Log: off"?

![grafik](https://user-images.githubusercontent.com/509535/151875020-09778aba-4ff9-4a67-bcf3-0e723b3455a1.png)

**Comment by markreidvfx** [comment]
Yes the sRGB ones have CLOG off. When Canon Log is on the image is suppose to have more dynamic range somehow, I think that's why its so dark. Even with a white level of 14888 the image can still seem to saturate the sensor beyond that, like in the CLOG3 one with a light.

![Capture](https://user-images.githubusercontent.com/814966/151883908-6441b89f-be48-480c-b28e-1d7a360b43ab.PNG)

I'm still trying to sort it out, but if you multiply the CLog1 by 8.0 CLog3 by 16.0 it kinda matches the linear levels of the sRGB. This kind of matches what the manual [says](https://cam.start.canon/en/C003/manual/html/UG-03_Shooting-2_0080.html).

attached is that CRM frame with the light
[2A5A2953_00.zip](https://github.com/dnglab/dnglab/files/7974699/2A5A2953_00.zip)

**Comment by cytrinox** [comment]
#100 is complete now, but I've not found the focal length value per sample/frame.
I will merge the PR and close this issue, I just need to add the test data to the test flow. Thanks for the contribution.
If you find out where the focal length is stored in CTMD records, please reopen this issue.

**Comment by markreidvfx** [comment]
Its near the start of CTMD packet. A short at offset 68 divided by a short at offset 70. I'm still digging into it, I'll let you know when I got the details sorted out.

**Comment by markreidvfx** [comment]
It location has been documented in the [exiftool](https://exiftool.org/TagNames/Canon.html#CTMD).
I'm still testing but here is my libraw [version](https://github.com/markreidvfx/LibRaw/commit/0016b48200489a74dcf89072bd724ee56ea86b6f)

**Comment by cytrinox** [comment]
It is documented by lclevy, too: https://github.com/lclevy/canon_cr3#ctmd-record-type-4-payload-focal-length-info
But for some reason, during my first tests this block had no valid data.
I tested it now again after refactored the CTMD parser code and now the data is correct... confusing but it works now.
Fixed in https://github.com/dnglab/dnglab/pull/105

Any more metadata that is useful for you that is not already located in CMT2 (general exif)?

**Comment by markreidvfx** [comment]
yes it is in a very odd format.  The exposure data, shutter, aperture and iso in the CMTD atom are useful too, but if I understand rust enough, you are parsing right? I'm not seeing the `iso &= 0x7fffffff` though?  as per [exiftool](https://github.com/exiftool/exiftool/blob/master/lib/Image/ExifTool/Canon.pm#L9087)
